name: "Deploy: SimplePriceFeed"

env:
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}
  POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}

on:
  workflow_dispatch:
    inputs:
      chain:
        description: "Chain name in lowercase"
        required: true
      confirmations:
        default: "2"
        description: "Number of block confirmations to wait before attempting verification"
        required: false
      description:
        description: "Description of the price feed, e.g. 'WBTC/USD'"
        required: true
      ref:
        default: "main"
        description: "Git ref to checkout"
        required: false

jobs:
  deploy-and-verify:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: "Setup Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install the dependencies"
        run: "yarn install --immutable"

      - name: "Build the TypeScript packages"
        run: "yarn build"

      - name: "Compile the contracts and generate TypeChain bindings"
        run: "yarn compile:sol"

      - name: "Build the TypeChain bindings"
        run: "yarn build:types"

      - name: "Deploy SimplePriceFeed"
        id: "deploy"
        run: >-
          yarn workspace @hifi/tasks hardhat
          deploy:contract:simple-price-feed --network "${{ github.event.inputs.chain }}"
          --description "${{ github.event.inputs.description }}"
          --confirmations "${{ github.event.inputs.confirmations }}"
          --set-output true

      - name: "Verify SimplePriceFeed"
        run: >-
          yarn workspace @hifi/protocol hardhat
          verify "${{ steps.deploy.outputs.simple-price-feed }}" --network "${{ github.event.inputs.chain }}"
