name: "Deploy: BalanceSheet"

env:
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}
  POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}

on:
  workflow_dispatch:
    inputs:
      chain:
        description: "Chain name in lowercase"
        required: true
      confirmations:
        default: "2"
        description: "Number of block confirmations to wait before attempting verification"
        required: false
      fintroller:
        description: "Address of the Fintroller contract"
        required: true
      oracle:
        description: "Address of the oracle contract"
        required: true
      ref:
        default: "main"
        description: "Git ref to checkout"
        required: false

jobs:
  deploy-and-verify:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: "Setup Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install the dependencies"
        run: "yarn install --immutable"

      - name: "Build the TypeScript packages"
        run: "yarn build"

      - name: "Compile the contracts and generate TypeChain bindings"
        run: "yarn workspace @hifi/protocol compile:sol"

      - name: "Deploy BalanceSheet"
        id: deploy
        run: >-
          yarn workspace @hifi/protocol hardhat
          deploy:contract:balance-sheet --network "${{ github.event.inputs.chain }}"
          --fintroller "${{ github.event.inputs.fintroller }}"
          --oracle "${{ github.event.inputs.oracle }}"
          --confirmations "${{ github.event.inputs.confirmations }}"
          --set-output true

      - name: "Verify BalanceSheet"
        run: >-
          yarn workspace @hifi/protocol hardhat
          verify "${{ steps.deploy.outputs.balance-sheet-implementation }}" --network "${{ github.event.inputs.chain }}"
